language: node_js
node_js:
    - "stable"
services:
    - mysql

before_install:
    - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
    - export DATABASE_NAME='test' && export DATABASE_USER='travis' && export DATABASE_PASSWORD='' &&  npm run test

# env:
#   - CXX=g++-4.8

# addons:
#   apt:
#     sources:
#       - ubuntu-toolchain-r-test
#     packages:
#       - g++-4.8