version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/data/mysql
    environment:
      MYSQL_ROOT_PASSWORD: redborderlicensepassworddb
      MYSQL_DATABASE: licenses_management
    ports:
      - "3306:3306"
  web: 
    volumes:
      - .:/app_license
    depends_on:
      - db
    links:
      - db:db
    build: 
      context: .
      dockerfile: dev.dockerfile
    image: licenses_app_dev
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: redborderlicensepassworddb
      DB_PORT: 3306
      DB_HOST: db
      DB_DATABASE: licenses_management
volumes:
  db_data: