version: '2'
services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/usr/src/mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: licenses_management
      MYSQL_USER: root
      MYSQL_PASSWORD: normal
  web: 
    depends_on:
      - db
    links:
      - db:db
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_PASSWORD: admin
      DB_HOST: db
volumes:
  db_data: